### ISSUE TITLE
why there is KeyError: -1 in prediction 

### ISSUE THREAD

**Issue by tianke0711** [dongjun-Lee/text-summarization-tensorflow#28]
when code run here::

   prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
       

        with open("result.txt", "a") as f:
            for line in prediction_output:
                summary = list()
                for word in line:
                    if word == "</s>":
                        break
                    if word not in summary:
                        summary.append(word)
                print(" ".join(summary), file=f)

    print('Summaries are saved to "result.txt"...')

there is error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-20-cc5ea0f5e9c8> in <module>
     27         print('prediction:', prediction.shape)
     28 
---> 29         prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
     30 
     31 

<ipython-input-20-cc5ea0f5e9c8> in <listcomp>(.0)
     27         print('prediction:', prediction.shape)
     28 
---> 29         prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
     30 
     31 

<ipython-input-20-cc5ea0f5e9c8> in <listcomp>(.0)
     27         print('prediction:', prediction.shape)
     28 
---> 29         prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
     30 
     31 

KeyError: -1

**Comment by dongjun-Lee** [comment]
Which tensorflow version are you using?

**Comment by tianke0711** [comment]
hi @dongjun-Lee  thanks for your response, I am using tensorflow==1.4.1. 
Could you left you email that so I can contact you to ask question, please!

**Comment by dongjun-Lee** [comment]
Hi @tianke0711 , it seems the error occurs because of your tensorflow version. Could you please try after upgrading tensorflow to >=1.8?
My e-mail is ganji1055@gmail.com.
Thank you.

**Comment by tianke0711** [comment]
> Hi @tianke0711 , it seems the error occurs because of your tensorflow version. Could you please try after upgrading tensorflow to >=1.8?
> My e-mail is [ganji1055@gmail.com](mailto:ganji1055@gmail.com).
> Thank you.

thanks for your kind comments. If I have issues, I will contact you.

**Comment by deepbodra97** [comment]
I am also getting a similar error
```
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
  File "test.py", line 36, in <listcomp>
    prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
  File "test.py", line 36, in <listcomp>
    prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
KeyError: -1
```

**Comment by yash-1997** [comment]
> > Hi @tianke0711 , it seems the error occurs because of your tensorflow version. Could you please try after upgrading tensorflow to >=1.8?
> > My e-mail is [ganji1055@gmail.com](mailto:ganji1055@gmail.com).
> > Thank you.
> 
> thanks for your kind comments. If I have issues, I will contact you.

Has upgrading to a higher version of tensorflow worked?

**Comment by yash-1997** [comment]
> I am also getting a similar error
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 36, in <module>
>     prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
>   File "test.py", line 36, in <listcomp>
>     prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
>   File "test.py", line 36, in <listcomp>
>     prediction_output = [[reversed_dict[y] for y in x] for x in prediction[:, 0, :]]
> KeyError: -1
> ```

Were you able to resolve the issue? If so, how?
