### ISSUE TITLE
UnicodeDecodeError using the sample data

### ISSUE THREAD

**Issue by wassimseif** [dongjun-Lee/text-summarization-tensorflow#6]
Hello,
I'm having some issues with preparing the data
Steps taken : 

1. Clone repo
2. Unzip sample_data.zip
3. python train.py

This is the error I'm getting 

```
Building dictionary...
Traceback (most recent call last):
  File "/Developer/Machine-Learning/Shared-folder/text-summarization-tensorflow/train.py", line 35, in <module>
    word_dict, reversed_dict, article_max_len, summary_max_len = build_dict("train", args.toy)
  File "/Developer/Machine-Learning/Shared-folder/text-summarization-tensorflow/utils.py", line 32, in build_dict
    train_article_list = get_text_list(train_article_path, toy)
  File "/Developer/Machine-Learning/Shared-folder/text-summarization-tensorflow/utils.py", line 25, in get_text_list
    return list(map(lambda x: clean_str(x.strip()), f.readlines()))
  File "/anaconda3/envs/deeplearning/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5241: ordinal not in range(128)
```

**Comment by wassimseif** [comment]
Fixed in #8
